### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by lukashlobil** [NathanWalker/nativescript-ng2-fonticon#15] opened 2017-01-02 09:59 UTC
Hi,
is it possible to enable Webpack (AOT) support for this plugin?
I cannot use .forRoot in my main ngModule.
Thank you

**Comment by NathanWalker** [comment] 2017-01-13 06:22
Hi @lukashlobil please remove your previous install of this plugin and install the new `2.0.0` version, also note the new name:
```
npm i nativescript-ngx-fonticon --save
```
Lemme know.

**Comment by zoeitsolutions** [comment] 2017-01-17 06:41
Hi @NathanWalker I used it in my main module and then had to use it in my LoginModule as well in order for it to work in my LoginModule's components. Is that correct?

**Comment by NathanWalker** [comment] 2017-01-17 06:56
@zoeitsolutions Yes that is correct, however just make sure you only call `TNSFontIconModule.forRoot` in your root module.

@lukashlobil curious if `2.0.0` was any better for you with webpack? If not can you provide a stacktrace and project setup?

**Comment by hypery2k** [comment] 2017-01-24 17:02
@NathanWalker 
I'm getting a wired error:
```
Error: Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule',
```
I'm using a shared module:
```

export function icons(): Object {
  return {
    'fa': 'fonts/font-awesome.css',
    'ion': 'fonts/ionicons.css'
  };
}

@NgModule({
  declarations: [
    CheckboxComponent,
    RadioButtonGroupComponent,
    RadioButtonComponent,
    MapComponent,
    LocalTimePipe,
    LocalDateTimePipe,
    SelectOneDialog,
    SimpleDialog
  ],
  imports: [
    CommonModule,
    NativeScriptModule,
    NativeScriptFormsModule,
    TNSFontIconModule.forRoot((icons)),
```

Any guess?

**Comment by hypery2k** [comment] 2017-01-24 17:19
I cannot find .metadata.json files in the plugin..

**Comment by patrickpereira** [comment] 2017-01-25 05:18
Hi @NathanWalker 

I'm getting the same error as @hypery2k 

ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule'

**Comment by hypery2k** [comment] 2017-02-03 13:48
@NathanWalker any ideas? Even if I move the Module to the root Module I'm getting the error:

```
ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /tmp/myapp/app/app.module.ts, resolving symbol AppModule in /tmp/myapp/app/app.module.ts
```

**Comment by hypery2k** [comment] 2017-02-03 13:49
BTW: I'm using Angular 2.4.3

**Comment by v-fedorov** [comment] 2017-02-06 17:16
Im having the same issue, @hypery2k were you able to resolve this?

**Comment by hypery2k** [comment] 2017-02-23 15:44
@NathanWalker Any solutions for this?
This doesn't work
```
  imports: [
    CommonModule,
    NativeScriptModule,
    NativeScriptFormsModule,
    TNSFontIconModule.forRoot({
      fa: 'fonts/font-awesome.css',
      ion: 'fonts/ionicons.css'
    }),
```

**Comment by v-fedorov** [comment] 2017-02-23 18:47
@hypery2k as a temp workaround I managed to get it working by creating and importing this file

https://gist.github.com/v-fedorov/945e33ffec6c7ad74133436aa23dd56c

**Comment by dgomezs** [comment] 2017-02-24 15:19
@NathanWalker having the same issue as reported here. Could you incorporte @v-fedorov solution or similar one?
Thank you very much in advanced. Getting closer to have my app full webpack

**Comment by NathanWalker** [comment] 2017-02-25 04:42
Hey absolutely, trying to get to this, sry for delay - next week should be better for me.

**Comment by hypery2k** [comment] 2017-02-25 05:50
@NathanWalker Maybe you could take a look at my fork. I think it should work, but currently getting errors during **tsc** The repo itself seems to have same setup issues.

**Comment by NathanWalker** [comment] 2017-02-25 07:07
Thanks @hypery2k does using the opaquetoken sol e the error for you?

**Comment by hypery2k** [comment] 2017-02-25 07:48
Can't say as I'm having issues with compiling all the stuff. I'll take a look later or at the beginning of the week.
If it's working I'll come back and update the PR

**Comment by patrickpereira** [comment] 2017-02-28 05:20
@hypery2k Any news on this one?

**Comment by hiddencaliber** [comment] 2017-03-06 23:01
Hi @NathanWalker / @hypery2k
I am also facing the same problem. Is there any update on this fix ?
Thanks,

**Comment by hypery2k** [comment] 2017-03-07 10:53
@NathanWalker: With my latest changes AoT build is working fine for me

**Comment by patrickpereira** [comment] 2017-03-07 11:44
Wicked!!! Let's get it merged @NathanWalker !!!

**Comment by dgomezs** [comment] 2017-03-09 14:04
hey @hypery2k how are you building the module from your fork? Looks like the file references.d.ts and if I remove it from compilation It cannot find 'file-system' module. Thank you in advanced

**Comment by dgomezs** [comment] 2017-03-10 07:03
hey @hypery2k or @NathanWalker  I installed the latest version of the plugin with the latest changes but Aot is still not working on my side. I still don't see the metadata for the plugin. I tried to generate it myself with the npm script without luck. Any thoughts?

**Comment by hypery2k** [comment] 2017-03-14 12:57
@NathanWalker: My fork as I pushed worked, the metadata is missing, see https://github.com/hypery2k/nativescript-ngx-fonticon/blob/master/package.json#L47

**Comment by lukashlobil** [comment] 2017-03-14 16:32
@hypery2k I will have to do a AOT build at the end of the week, this is the last plugin hindering from doing that. Is there a way I can use your repo? (wanted to post this in your repo, but issues forum is not there since it is a fork).

**Comment by YvesCandel** [comment] 2017-03-17 10:03
Would love to see this merged/fixed soon. This is the only plugin stopping us from using webpack.

**Comment by hypery2k** [comment] 2017-03-20 07:56
everyone can give my PR a try:
```
npm install nativescript-ngx-fonticon@next
```

**Comment by YvesCandel** [comment] 2017-03-20 09:41
Your PR brings up an error:

"file:///app/app.module.js:9:42: JS ERROR SyntaxError: Importing binding name 'TNSFontIconPurePipe' is not found."

Any thoughts?

**Comment by YvesCandel** [comment] 2017-03-20 10:18
Still not working with aot...

`ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /Users/etc/app/app.module.ts, resolving symbol AppModule in /Users/etc/app/app.module.ts`

Using it like this in my app.module.ts:

`TNSFontIconModule.forRoot({ 'fa': 'font-awesome.css' })`

**Comment by hypery2k** [comment] 2017-03-20 12:44
With the help of an sample app I've added I'm able to reproduce the error. Looking at this later the week

**Comment by hypery2k** [comment] 2017-03-20 12:44
@NathanWalker I've added a npm run script `npm run e2e` which tests the plugin in an AoT sample App

**Comment by hypery2k** [comment] 2017-03-23 06:58
@all can give my PR a try:
```
npm install nativescript-ngx-fonticon@next
```

**Comment by cjdreiss** [comment] 2017-03-23 19:25
@v-fedorov 's solution helped my app AoT compile and get me to be able to launch the app.  Not sure if it works or not in terms of displaying icons because I had so many other runtime issues with AoT that I ended up giving up after nearly a day of changing things.

**Comment by MartoYankov** [comment] 2017-03-24 13:30
@hypery2k I was able to test this and now it works for Android builds. It fails on iOS with the same error: 
ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported.

**Comment by ADjenkov** [comment] 2017-03-27 06:33
@hypery2k same problem here with the iOS as MIYankov said (the above comment)

**Comment by hypery2k** [comment] 2017-03-27 06:34
did you completely removed the platform and hooks?

**Comment by ADjenkov** [comment] 2017-03-27 07:34
Yes, I've just tried that (removing platforms, node_modules and hooks folders). 
No result

"ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported."

**Comment by hypery2k** [comment] 2017-03-27 07:46
did you tried `npm run ns-bundle ios -- --clean`?
Which exact version of the module you're using?

**Comment by ADjenkov** [comment] 2017-03-27 08:02
Yes it works with `npm run ns-bundle ios --start-app --clean` 
Using `next` version of the module (^2.1.2-PR-26-3). Thanks!

**Comment by hypery2k** [comment] 2017-03-27 08:43
@NathanWalker Should we release a patch version with this PR and afterwards cleanup the code, regarding the sample apps vs. end2end test ?

**Comment by YvesCandel** [comment] 2017-03-31 08:48
If I add it as ^2.1.2-PR-26-3 to package.json and npm install, it doesn't seem to work.

But if i, afterwards, do an "npm install nativescript-ngx-fonticon@next --save", it works fine.

Looking forward to having you publish the new version!

**Comment by hypery2k** [comment] 2017-03-31 08:53
you normally have to clean everything out, with `--clean`

**Comment by lukashlobil** [comment] 2017-04-03 14:25
@hypery2k Even with 

>  "nativescript-ngx-fonticon": "^2.1.2-PR-26-3"

I still get:

> ERROR in Error encountered resolving symbol values statically. Calling function 'TNSFontIconModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in .../app.module.ts, resolving symbol AppModule in .../app.module.ts

any thoughts please?

**Comment by Yamilquery** [comment] 2017-04-03 16:19
@lukashlobil  In my case, using version 2.1.2-PR-26-3. What I did was delete the / platforms folder and use the following command:

`npm run build-ios-bundle -- --release --for-device --teamId <your_teamId>`

But...
```
CONSOLE LOG file:///app/bundle.js:4571:24: Collections to load: fa
CONSOLE LOG file:///app/bundle.js:4595:24: ----------
CONSOLE LOG file:///app/bundle.js:4596:24: Loading collection 'fa' from file: ./assets/font-awesome.css
CONSOLE ERROR file:///app/vendor.js:59780:26: Unhandled Promise rejection: Animation cancelled. ;
```

And my icons show "undefined"...

In dev mode:
`tns run ios --emulator`

I'm getting this:

```
1   0x1039e733c -[TNSRuntime executeModule:referredBy:]
2   0x103501389 main
3   0x1089ee65d start
file:///app/shared/menu/menu.component.ts:10:39: JS ERROR SyntaxError: Importing binding name 'TNSFontIconPurePipe' is not found.
```

**Comment by lukashlobil** [comment] 2017-04-03 17:20
Here is my package,json and app.module: https://gist.github.com/lukashlobil/e7e81852cdc9e746fa7e79ac03cc6545

**Comment by lukashlobil** [comment] 2017-04-07 12:25
So, I got it working with AOT, but now it won't work without AOT :-( anyone experiencing the same?

**Comment by hypery2k** [comment] 2017-04-08 06:12
could you try with nativescript-ngx-fonticon@2.1.2-PR-26-12

**Comment by ErikGrijzen** [comment] 2017-04-10 20:10
I have the same issue. AOT compilation works fine with "2.1.2-PR-26-12".

But now DEV mode is broken and shows:
> JS ERROR SyntaxError: Importing binding name 'TNSFontIconPurePipe' is not found.

**Comment by hypery2k** [comment] 2017-04-11 05:39
so you're justing doing a `tns run ios --emulator`?

**Comment by YvesCandel** [comment] 2017-04-11 08:40
My build now throws the following error using your PR:

ERROR in ../~/nativescript-ngx-fonticon/nativescript-ngx-fonticon.js
Module not found: Error: Can't resolve 'tslib' in '..users..etc.../node_modules/nativescript-ngx-fonticon'

**Comment by YvesCandel** [comment] 2017-04-11 08:57
FYI: My build uses webpack to bundle the app.

I've found this comment:

https://github.com/s-panferov/awesome-typescript-loader/issues/250#issuecomment-279325365

Your tslib dependency is a dev dependency rather than a direct dependency. That could be the issue no?

**Comment by hypery2k** [comment] 2017-04-11 11:03
you can test the latest snapshot when CI build [finishes](https://martinreinhardt-online.de/jenkins/blue/organizations/jenkins/NPM%2Fnativescript-ngx-fonticon/detail/PR-26/14/pipeline):

**Comment by YvesCandel** [comment] 2017-04-11 12:07
@hypery2k Thanks! It's working now :)

**Comment by hypery2k** [comment] 2017-04-11 12:10
thanks for testing ;)

**Comment by YvesCandel** [comment] 2017-04-11 12:16
No problem. The bad news is that the regular "tns run ios --emulator" (so, no webpack) still throws the following error:

"file:///app/app.module.js:9:42: JS ERROR SyntaxError: Importing binding name 'TNSFontIconPurePipe' is not found."

I'm not even using it anywhere in my solution... just the regular TNSFontIconPipe.

**Comment by hypery2k** [comment] 2017-04-13 08:58
can you post your tsconfig?

**Comment by YvesCandel** [comment] 2017-04-13 08:59
tsconfig.json:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "lib": [
            "es2016"
        ]
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

tsconfig.aot.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true,
    "types": [],
    "baseUrl": ".",
    "paths": {
      "ui/*": ["node_modules/tns-core-modules/ui/*"],
      "platform": ["node_modules/tns-core-modules/platform"],
      "image-source": ["node_modules/tns-core-modules/image-source"],
      "xml": ["node_modules/tns-core-modules/xml"],
      "xhr": ["node_modules/tns-core-modules/xhr"],
      "text": ["node_modules/tns-core-modules/text"],
      "data": ["node_modules/tns-core-modules/data"],
      "fetch": ["node_modules/tns-core-modules/fetch"],
      "trace": ["node_modules/tns-core-modules/trace"],
      "fps-meter": ["node_modules/tns-core-modules/fps-meter"],
      "color": ["node_modules/tns-core-modules/color"],
      "application-settings": ["node_modules/tns-core-modules/application-settings"],
      "http": ["node_modules/tns-core-modules/http"],
      "camera": ["node_modules/tns-core-modules/camera"],
      "console": ["node_modules/tns-core-modules/console"],
      "timer": ["node_modules/tns-core-modules/timer"],
      "utils": ["node_modules/tns-core-modules/utils"],
      "location": ["node_modules/tns-core-modules/location"],
      "file-system": ["node_modules/tns-core-modules/file-system"],
      "application": ["node_modules/tns-core-modules/application"],
      "image-asset": ["node_modules/tns-core-modules/image-asset"],
      "connectivity": ["node_modules/tns-core-modules/connectivity"],
      "globals": ["node_modules/tns-core-modules/globals"]

    }
   },
  "exclude": [
      "node_modules",
      "platforms"
  ],
  "angularCompilerOptions": {
    "skipMetadataEmit": true,
    "genDir": "./"
  }
}
```

**Comment by hypery2k** [comment] 2017-04-13 13:12
could try this tsconfig?
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "removeComments": true,
        "experimentalDecorators": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipDefaultLibCheck": true,
        "skipLibCheck": true,
        "importHelpers": true,
        "types": [
            "jasmine"
        ],
        "lib": [
            "es2015",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}

```

**Comment by YvesCandel** [comment] 2017-04-13 13:19
Same result...

**Comment by buuhuu** [comment] 2017-04-14 11:27
The problem seems to be that nativescript-ngx-fonticon is an es2015 module and the actual issue is caused by 

`import * as tslib from 'tslib'`

Webpack seems to be able to build that without any problems, but on the other hand the runtime cannot handle that. (Just a guess ;) )

**Comment by buuhuu** [comment] 2017-04-14 17:12
I made another fix https://github.com/hypery2k/nativescript-ngx-fonticon/pull/2 that resolves the crash on android:

"Trying to link invalid 'this' to Java object".

For me this is now working for android and ios, both webpack and tns build. @hypery2k can you publish a new tag for the PR?

**Comment by hypery2k** [comment] 2017-04-14 18:54
you could try with `nativescript-ngx-fonticon@2.1.2-PR-26-16`

**Comment by YvesCandel** [comment] 2017-04-19 12:35
I can confirm that 2.1.2-PR-26-16 works both with and without webpack for our app!

**Comment by hypery2k** [comment] 2017-04-20 16:14
Version 2.2.0 is published now

**Closed as completed by hypery2k** 2017-04-20 16:14 UTC
